language: java
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
jdk: oraclejdk8
before_install:
  - nvm install 5
  - npm install -g chromedriver
  - npm install
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
script: npm test
branches:
  only: master
cache:
  directories: node_modules
